module.exports = {
  PORT: PROCESS.ENV.PORT,
  MONGODB_URI: PROCESS.ENV.MONGODB_URI,
  GOOGLE_CLIENT_ID: PROCESS.ENV.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: PROCESS.ENV.GOOGLE_CLIENT_SECRET,
  COOKIE_KEY: PROCESS.ENV.COOKIE_KEY,
  REDIRECT: "",
  CLOUD_NAME: PROCESS.ENV.CLOUD_NAME,
  CLOUD_SECRET: PROCESS.ENV.CLOUD_SECRET,
  CLOUD_API_KEY: PROCESS.ENV.API_KEY,
};